version: '2'

services:
  db:
    restart: always
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: musicsearch
  web:
    restart: always
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ["/tmp/wait-for-it.sh", "db:5432", "--", "python manage.py runserver 0.0.0.0:8000"]
